//! 编排礼仪 Skill(`mini-term-orchestrator`)的投放:让编排者一开箱就会用控制 CLI。
//!
//! 工单 09 留档的那条链路。落盘形状与 `ssh_registry`(mini-term-ssh)同一套
//! (底座在 `skill_files`):`<project>/.claude/skills/<name>/SKILL.md` +
//! `<project>/.codex/skills/<name>/SKILL.md`,Claude 版带 `allowed-tools` 免审批、
//! Codex 版不带;`.gitignore` 幂等追加;Codex 项目信任。**触发时机不同**:
//!
//! - mini-term-ssh 是**按项目**的开关,勾选那一刻就知道投到哪;
//! - 编排能力挂在**启动器**上(ADR 0003 的信任根),而编排者跑在哪个项目要到
//!   起 pane 那一刻才知道 —— 同一条启动器今天在前端项目起、明天在后端项目起。
//!   于是投放跟着**令牌**走:`store::panes::start_pty` 发令牌的同一处
//!   [`deploy`];编排者 pane 关掉、该项目再没有别的编排者活着时 [`withdraw`]
//!   (`store::ai::dispose_terminal`)。Skill 与令牌是同一项能力的两半,
//!   一个不发另一个也不投(SSH 远程项目两样都没有)。
//!
//! # 正文只有一份
//!
//! 仓内 `.claude/skills/mini-term-orchestrator/SKILL.md` 是**唯一源头**
//! (它同时服务于在本仓里开发 mini-term 的会话),这里 `include_str!` 编进
//! 二进制,投放时只换掉两个 HTML 注释标记之间的「CLI 在哪」一段(嵌入真实的
//! sidecar 路径与各 shell 的调用写法),并在 Claude 版加 `allowed-tools`。
//! 标记缺失时渲染失败 —— 由测试钉住,改源文件时别把标记删了。
//!
//! # 不碰别人的文件
//!
//! 目标路径上若已有一份**不带生成标记**的 SKILL.md(用户手放的、或本仓自己
//! 那份被 git 跟踪的源文件 —— 在 mini-term 项目里开编排者就会撞上它),
//! 投放跳过、收回也不删。生成物一律带 `<!-- generated by mini-term` 标记,
//! 只有带标记的才归本模块管;两份都是别人的时,`.gitignore` 与 Codex 信任
//! 也一并不动。
//!
//! # 线程口径
//!
//! [`deploy`] 在主线程**同步**跑:它必须赶在启动命令敲进 shell 之前落盘
//! (agent 只在启动时读 skills 目录),两个小文件加一次 `.gitignore` 是毫秒级。
//! [`withdraw`] 没人等它,调用方丢 `background_executor`。

use std::path::Path;

use mt_core::atomic_write;

use crate::skill_files::{
    append_gitignore_entries, prune_empty_skill_dirs, quote_posix_single,
    quote_powershell_single, skill_paths, trust_project_in_codex, validate_project_dir,
};

/// skill 目录名,必须与源文件 frontmatter 的 `name` 一致(Claude Code 按目录名
/// 找 skill)。
pub const SKILL_DIR_NAME: &str = "mini-term-orchestrator";

/// 源头:仓内那份 SKILL.md(路径相对本文件)。
const SKILL_SOURCE: &str = include_str!("../../../.claude/skills/mini-term-orchestrator/SKILL.md");

/// 源文件里圈出「CLI 在哪」那一段的两个标记。
const CLI_SECTION_START: &str = "<!-- cli-location:start -->";
const CLI_SECTION_END: &str = "<!-- cli-location:end -->";

/// 生成标记。前缀与 mini-term-ssh 的一致;[`is_generated`] 只认前缀,
/// 括号里的说明改了也不影响旧生成物被认领。
const GENERATED_MARKER: &str =
    "<!-- generated by mini-term; do not edit (rewritten whenever an orchestrator starts in this project) -->";
const GENERATED_PREFIX: &str = "<!-- generated by mini-term";

const GITIGNORE_HEADER: &str = "# mini-term orchestrator skill（本机相关生成物，勿提交）";
const GITIGNORE_ENTRIES: &[&str] = &[
    ".claude/skills/mini-term-orchestrator/",
    ".codex/skills/mini-term-orchestrator/",
];

/// `mt-agent-cli` sidecar 的绝对路径(与主程序同目录的兄弟 bin)。
///
/// dev 下 `stage-sidecars.mjs` 把 sidecar 裸名就位到根 `target/debug`
/// (与 `mini-term.exe` 同目录),与发布包布局一致。
fn agent_cli_binary_path() -> Result<String, String> {
    let exe = std::env::current_exe().map_err(|e| format!("无法获取当前程序路径: {}", e))?;
    let dir = exe
        .parent()
        .ok_or_else(|| "无法获取程序所在目录".to_string())?;
    let bin_name = if cfg!(windows) {
        "mt-agent-cli.exe"
    } else {
        "mt-agent-cli"
    };
    Ok(dir.join(bin_name).to_string_lossy().to_string())
}

// ─── 渲染 ───

/// 把仓内源文件渲染成投放版。`with_allowed_tools` 区分 Claude 版(true)与
/// Codex 版(false)。
fn render_skill_md(binary_path: &str, with_allowed_tools: bool) -> Result<String, String> {
    render_from(SKILL_SOURCE, binary_path, with_allowed_tools, cfg!(windows))
}

/// 渲染的纯函数半场,便于单测拿自造的源文本喂。
///
/// `wsl_interop`:要不要给出 WSL 里调 Windows 二进制的写法(只在 Windows 宿主
/// 上有意义 —— 启动器可以绑 wsl-bash,那时 agent 跑在 WSL 里)。
fn render_from(
    source: &str,
    binary_path: &str,
    with_allowed_tools: bool,
    wsl_interop: bool,
) -> Result<String, String> {
    // 源文件是随仓的文本,签出时可能被换成 CRLF;渲染只认 LF。
    let source = source.replace("\r\n", "\n");
    let rest = source
        .strip_prefix("---\n")
        .ok_or("SKILL.md 源文件缺少 frontmatter")?;
    let end = rest
        .find("\n---\n")
        .ok_or("SKILL.md 源文件的 frontmatter 未闭合")?;
    let frontmatter = &rest[..end];
    let body = &rest[end + "\n---\n".len()..];

    let start = body
        .find(CLI_SECTION_START)
        .ok_or("SKILL.md 源文件缺少 cli-location:start 标记")?;
    let stop = body
        .find(CLI_SECTION_END)
        .ok_or("SKILL.md 源文件缺少 cli-location:end 标记")?;
    if stop < start {
        return Err("SKILL.md 源文件的 cli-location 标记顺序颠倒".to_string());
    }
    let before = body[..start].trim_matches('\n');
    let after = body[stop + CLI_SECTION_END.len()..].trim_matches('\n');

    // 与 mini-term-ssh 同一写法:Windows 版 Claude Code 的 shell 工具可能是 Bash
    // 或 PowerShell,两个都列;整行是 YAML 单引号标量,路径里的撇号要双写。
    let allowed_tools_line = if with_allowed_tools {
        let yaml_safe = binary_path.replace('\'', "''");
        format!("allowed-tools: 'Bash(\"{yaml_safe}\" *), PowerShell(\"{yaml_safe}\" *)'\n")
    } else {
        String::new()
    };
    let cli = render_cli_section(binary_path, wsl_interop);

    Ok(format!(
        "---\n{frontmatter}\n{allowed_tools_line}---\n\n{GENERATED_MARKER}\n\n{before}\n\n{cli}\n\n{after}\n"
    ))
}

/// 「CLI 在哪、怎么调」那一段:真实路径 + 各 shell 的写法。
///
/// 正文其余部分的示例都写作裸 `mt-agent-cli`,这里交代一句「示例里的
/// `mt-agent-cli` 指这个带引号的路径」,比把几十处示例都替换成长路径可读。
fn render_cli_section(binary_path: &str, wsl_interop: bool) -> String {
    let bash = quote_posix_single(binary_path);
    let powershell = quote_powershell_single(binary_path);
    let mut forms = vec![format!("    {bash} <command> ...    # Bash / Git Bash")];
    if wsl_interop {
        forms.push(format!(
            "    \"$(wslpath {bash})\" <command> ...    # WSL (Windows interop)"
        ));
    }
    forms.push(format!(
        "    & {powershell} <command> ...    # PowerShell (the call operator `&` is required)"
    ));
    format!(
        "The CLI binary (quote the path, it may contain spaces):\n\n    \"{binary_path}\"\n\n\
How to invoke it from each shell:\n\n{}\n\n\
In the examples below, `mt-agent-cli` stands for that quoted path. Run it with\n\
`--help` once; the exit codes and per-command notes there are authoritative.\n\
Every command prints JSON on success.",
        forms.join("\n")
    )
}

// ─── 落盘 / 收回 ───

/// 这份文件是不是本模块写的。读不出来(权限 / 编码)按「别人的」处理 —— 宁可
/// 不投,也不覆盖一份来历不明的文件。
fn is_generated(path: &Path) -> bool {
    std::fs::read_to_string(path)
        .map(|s| s.contains(GENERATED_PREFIX))
        .unwrap_or(false)
}

/// 写两份 SKILL.md,返回**真写了几份**。已有的非生成文件跳过不动。
fn write_skill_files(project_dir: &Path, binary_path: &str) -> Result<usize, String> {
    let mut written = 0;
    for (path, with_allowed_tools) in skill_paths(project_dir, SKILL_DIR_NAME) {
        if path.exists() && !is_generated(&path) {
            eprintln!(
                "[orchestrator_skill] {} 不是 mini-term 生成的,保留原样",
                path.display()
            );
            continue;
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("创建 skill 目录失败 {}: {}", parent.display(), e))?;
        }
        let content = render_skill_md(binary_path, with_allowed_tools)?;
        atomic_write(&path, content.as_bytes())
            .map_err(|e| format!("写入 {} 失败: {}", path.display(), e))?;
        written += 1;
    }
    Ok(written)
}

/// 删本模块生成的 SKILL.md 及其空壳目录。不带生成标记的文件不碰;不存在视为
/// 已收回(幂等)。
fn remove_skill_files(project_dir: &Path) -> Result<(), String> {
    for (path, _) in skill_paths(project_dir, SKILL_DIR_NAME) {
        if !path.exists() || !is_generated(&path) {
            continue;
        }
        std::fs::remove_file(&path).map_err(|e| format!("删除 {} 失败: {}", path.display(), e))?;
        prune_empty_skill_dirs(&path);
    }
    Ok(())
}

// ─── 公开入口 ───

/// 把编排礼仪 Skill 投进 `project_dir`。**同步阻塞**,调用点在起编排者 pane
/// 发令牌的那一行(`store::panes::start_pty`),必须赶在启动命令之前。
///
/// 只有 SKILL.md 写失败才算失败(编排者会拿不到礼仪);`.gitignore` 与 Codex
/// 信任是附带项,失败记 stderr 不拦。两份都被别人的文件占着时什么都不动。
pub fn deploy(project_dir: &str) -> Result<(), String> {
    let dir = validate_project_dir(project_dir)?;
    let binary_path = agent_cli_binary_path()?;

    let written = write_skill_files(&dir, &binary_path)?;
    if written == 0 {
        return Ok(());
    }
    if let Err(e) = trust_project_in_codex(&dir) {
        eprintln!("[orchestrator_skill] 写 Codex 项目信任失败(不影响投放): {e}");
    }
    if let Err(e) = ignore_generated_files(&dir, written) {
        eprintln!("[orchestrator_skill] 追加 .gitignore 失败(不影响投放): {e}");
    }
    Ok(())
}

/// 把生成物目录追加进 `.gitignore` —— **两份都是自己写的才碰**。
///
/// 有一份是别人的(用户手放的、或本仓被 git 跟踪的源文件)说明这个项目在自己管
/// 这些文件,再把它的目录写进 `.gitignore` 是帮倒忙:在 mini-term 仓里开编排者
/// 就会把源文件所在目录 ignore 掉(2026-09-02 踩到)。
fn ignore_generated_files(project_dir: &Path, written: usize) -> Result<(), String> {
    if written < skill_paths(project_dir, SKILL_DIR_NAME).len() {
        return Ok(());
    }
    append_gitignore_entries(project_dir, GITIGNORE_HEADER, GITIGNORE_ENTRIES)
}

/// 从 `project_dir` 收回本模块投放的 Skill。**阻塞**,丢 `background_executor`。
///
/// Codex 信任与 `.gitignore` 条目保留(与 mini-term-ssh 同一口径:无害,且无法
/// 可靠区分是否本功能所加)。
pub fn withdraw(project_dir: &str) -> Result<(), String> {
    let dir = validate_project_dir(project_dir)?;
    remove_skill_files(&dir)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn unique_test_dir(label: &str) -> PathBuf {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("mt-orch-skill-test-{label}-{ts}"));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    const WIN_BIN: &str = r"C:\Program Files\mini term\mt-agent-cli.exe";

    fn claude_path(dir: &Path) -> PathBuf {
        skill_paths(dir, SKILL_DIR_NAME)[0].0.clone()
    }

    fn codex_path(dir: &Path) -> PathBuf {
        skill_paths(dir, SKILL_DIR_NAME)[1].0.clone()
    }

    // ─── 源文件的形状 ───

    /// 仓内源文件必须渲染得出来 —— 标记被删、frontmatter 被改坏都在这里红。
    #[test]
    fn 仓内源文件渲染得出来() {
        let md = render_skill_md(WIN_BIN, true).expect("源文件形状被改坏了");
        assert!(md.starts_with("---\nname: mini-term-orchestrator\n"), "got:\n{md}");
        // 目录名与 frontmatter 的 name 必须一致,Claude Code 按目录名找 skill
        assert!(md.contains(&format!("name: {SKILL_DIR_NAME}\n")));
        assert!(md.contains(GENERATED_MARKER));
        // 标记本身不进生成物
        assert!(!md.contains(CLI_SECTION_START));
        assert!(!md.contains(CLI_SECTION_END));
        // 源文件里那个举例路径不该留下来,换成真路径
        assert!(!md.contains("E:\\Program Files\\Mini-Term"), "got:\n{md}");
        assert!(md.contains(&format!("    \"{WIN_BIN}\"")));
        // 正文其余部分原样保留(抽几句礼仪铁律钉一下)
        assert!(md.contains("Never answer for a human"));
        assert!(md.contains("Do not `send` immediately after `start-session`"));
        // 推送模型(ADR 0004):汇报自己来,以及认出汇报的那个标记
        assert!(md.contains("Results are pushed to you"));
        assert!(md.contains("[mini-term]"));
    }

    #[test]
    fn claude_版带_allowed_tools_codex_版不带() {
        let claude = render_skill_md(WIN_BIN, true).unwrap();
        let codex = render_skill_md(WIN_BIN, false).unwrap();
        assert!(claude.contains(&format!(
            "allowed-tools: 'Bash(\"{WIN_BIN}\" *), PowerShell(\"{WIN_BIN}\" *)'\n---\n"
        )));
        assert!(!codex.contains("allowed-tools"));
        // 除了这一行,两版一字不差
        assert_eq!(
            claude.replace(
                &format!("allowed-tools: 'Bash(\"{WIN_BIN}\" *), PowerShell(\"{WIN_BIN}\" *)'\n"),
                ""
            ),
            codex
        );
    }

    #[test]
    fn 各_shell_的调用写法都在() {
        let md = render_from(SKILL_SOURCE, WIN_BIN, true, true).unwrap();
        assert!(md.contains(r#"    'C:\Program Files\mini term\mt-agent-cli.exe' <command> ...    # Bash"#));
        assert!(md.contains(r#"wslpath 'C:\Program Files\mini term\mt-agent-cli.exe'"#));
        assert!(md.contains(r#"    & 'C:\Program Files\mini term\mt-agent-cli.exe' <command> ...    # PowerShell"#));
        // 非 Windows 宿主没有 WSL 那一行
        let md = render_from(SKILL_SOURCE, "/opt/mini-term/mt-agent-cli", true, false).unwrap();
        assert!(!md.contains("wslpath"));
        assert!(md.contains("    '/opt/mini-term/mt-agent-cli' <command> ..."));
    }

    #[test]
    fn 路径里的撇号按各家规则转义() {
        let md = render_from(SKILL_SOURCE, r"C:\Users\O'Brien\mt-agent-cli.exe", true, true).unwrap();
        // YAML 单引号标量:双写
        assert!(md.contains(r#"Bash("C:\Users\O''Brien\mt-agent-cli.exe" *)"#), "got:\n{md}");
        // POSIX 单引号:'"'"'
        assert!(md.contains(r#"wslpath 'C:\Users\O'"'"'Brien\mt-agent-cli.exe'"#));
        // PowerShell 单引号:双写
        assert!(md.contains(r#"& 'C:\Users\O''Brien\mt-agent-cli.exe' <command>"#));
        // 正文(引号之外)保留原始撇号
        assert!(md.contains(r#"    "C:\Users\O'Brien\mt-agent-cli.exe""#));
    }

    #[test]
    fn 源文件缺标记时拒绝渲染() {
        let no_start = SKILL_SOURCE.replace(CLI_SECTION_START, "");
        assert!(render_from(&no_start, WIN_BIN, true, true).is_err());
        let no_end = SKILL_SOURCE.replace(CLI_SECTION_END, "");
        assert!(render_from(&no_end, WIN_BIN, true, true).is_err());
        let no_frontmatter = SKILL_SOURCE.trim_start_matches("---\n").to_string();
        assert!(render_from(&no_frontmatter, WIN_BIN, true, true).is_err());
    }

    /// 签出成 CRLF 的源文件也得渲染得出来(autocrlf 的坑)。
    #[test]
    fn crlf_源文件照样渲染() {
        let crlf = SKILL_SOURCE.replace('\n', "\r\n");
        let md = render_from(&crlf, WIN_BIN, true, true).unwrap();
        assert!(!md.contains('\r'));
        assert!(md.starts_with("---\nname: mini-term-orchestrator\n"));
    }

    // ─── 落盘 / 收回 ───

    #[test]
    fn 投放写两份并带生成标记() {
        let dir = unique_test_dir("write");
        assert_eq!(write_skill_files(&dir, WIN_BIN).unwrap(), 2);
        let claude = std::fs::read_to_string(claude_path(&dir)).unwrap();
        let codex = std::fs::read_to_string(codex_path(&dir)).unwrap();
        assert!(claude.contains("allowed-tools"));
        assert!(!codex.contains("allowed-tools"));
        assert!(is_generated(&claude_path(&dir)));
        assert!(is_generated(&codex_path(&dir)));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn 重复投放整文件覆盖() {
        let dir = unique_test_dir("overwrite");
        write_skill_files(&dir, r"C:\old\mt-agent-cli.exe").unwrap();
        write_skill_files(&dir, r"C:\new\mt-agent-cli.exe").unwrap();
        let md = std::fs::read_to_string(claude_path(&dir)).unwrap();
        assert!(md.contains(r"C:\new\mt-agent-cli.exe"));
        assert!(!md.contains(r"C:\old\mt-agent-cli.exe"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// 别人的文件(用户手放的 / 本仓那份被 git 跟踪的源文件)不覆盖。
    #[test]
    fn 不覆盖别人的_skill_文件() {
        let dir = unique_test_dir("foreign");
        let claude = claude_path(&dir);
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(&claude, SKILL_SOURCE).unwrap();

        // Claude 那份是别人的 → 跳过;Codex 那份没有 → 照写
        let written = write_skill_files(&dir, WIN_BIN).unwrap();
        assert_eq!(written, 1);
        assert_eq!(std::fs::read_to_string(&claude).unwrap(), SKILL_SOURCE);
        assert!(codex_path(&dir).exists());
        // 有一份是别人的:`.gitignore` 一个字都不动(源文件目录不许被 ignore 掉)
        ignore_generated_files(&dir, written).unwrap();
        assert!(!dir.join(".gitignore").exists(), "别人的目录不许写进 .gitignore");

        // 收回同样只动自己写的那份
        remove_skill_files(&dir).unwrap();
        assert!(claude.exists(), "别人的文件不许删");
        assert!(!codex_path(&dir).exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// 两份都是自己写的,`.gitignore` 才追加两个生成物目录。
    #[test]
    fn 两份都自己写时才追加_gitignore() {
        let dir = unique_test_dir("gitignore");
        let written = write_skill_files(&dir, WIN_BIN).unwrap();
        assert_eq!(written, 2);
        ignore_generated_files(&dir, written).unwrap();
        let content = std::fs::read_to_string(dir.join(".gitignore")).unwrap();
        for entry in GITIGNORE_ENTRIES {
            assert!(content.contains(entry), "缺 {entry}:\n{content}");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn 收回删文件并收空壳() {
        let dir = unique_test_dir("remove");
        write_skill_files(&dir, WIN_BIN).unwrap();
        remove_skill_files(&dir).unwrap();
        assert!(!dir.join(".claude").exists(), "空壳目录应被清理");
        assert!(!dir.join(".codex").exists(), "空壳目录应被清理");
        assert!(dir.exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn 收回不动旁边的内容() {
        let dir = unique_test_dir("keep-sibling");
        write_skill_files(&dir, WIN_BIN).unwrap();
        std::fs::write(dir.join(".claude").join("settings.local.json"), b"{}").unwrap();
        let other = dir.join(".claude").join("skills").join("mini-term-ssh");
        std::fs::create_dir_all(&other).unwrap();
        std::fs::write(other.join("SKILL.md"), b"ssh").unwrap();

        remove_skill_files(&dir).unwrap();

        assert!(!claude_path(&dir).exists());
        assert!(dir.join(".claude").join("settings.local.json").exists());
        assert!(other.join("SKILL.md").exists(), "mini-term-ssh 那份是别的注册器的");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn 从未投放过时收回不报错() {
        let dir = unique_test_dir("remove-absent");
        remove_skill_files(&dir).unwrap();
        withdraw(&dir.to_string_lossy()).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn 项目目录没了就报错而不是凭空建目录() {
        assert!(withdraw("/definitely/not/a/real/dir/xyz123").is_err());
        assert!(deploy("/definitely/not/a/real/dir/xyz123").is_err());
    }

    /// `.gitignore` 追加的是本 skill 自己的两个目录,与 mini-term-ssh 的条目
    /// 互不覆盖(同一个项目可能两样都开)。
    #[test]
    fn gitignore_条目是本_skill_自己的() {
        for entry in GITIGNORE_ENTRIES {
            assert!(entry.contains(SKILL_DIR_NAME));
            assert!(!entry.contains("mini-term-ssh"));
        }
    }
}
