//! SSH 工具(CLI + Skill)按项目启用/停用(audit #28 的注册半场)。
//!
//! 自 `src-tauri/src/ssh_skill_registry.rs`(681 行)+ `ssh_mcp_registry.rs`
//! (462 行)合并移植而来 —— 后者在装机版就只剩「摘除历史 MCP 注册」的读侧
//! 清理职责,只被前者调用,没有独立入口,故并进同一模块的 `legacy_mcp` 段。
//!
//! **注册路径与文件格式一字不改**:`mini-term-ssh` skill 在装机版就是这套
//! 生成物,两个版本轮流跑时必须互认。
//!
//! 启用时(全部幂等):
//! - 写 `<project>/.claude/skills/mini-term-ssh/SKILL.md`(含 `allowed-tools`)
//! - 写 `<project>/.codex/skills/mini-term-ssh/SKILL.md`(无 `allowed-tools`)
//! - `.gitignore` 幂等追加两个 skill 目录
//! - Codex 项目信任保留(项目级 `.codex/` 内容大概率仍要求 trusted,写入无害)
//! - **迁移清理**:摘除该项目的旧 MCP 注册(`.mcp.json` 条目、项目 Codex 配置、
//!   Claude 免审批白名单 —— 他人条目毫发无损)
//!
//! 停用时:删两份 SKILL.md 及空目录(`skills/` 若空一并删除,不留空壳),
//! 并同样执行 MCP 迁移清理兜底存量。Codex 信任与 `.gitignore` 不回收。
//!
//! # 线程口径
//!
//! [`enable`] / [`disable`] 都是**同步阻塞**的文件 IO(还要跨盘写 home 下的
//! 配置),调用方丢 `cx.background_executor().spawn(...)`,与 `mt_project::git`
//! 同一条纪律。

use std::path::{Path, PathBuf};

use mt_core::atomic_write;
use serde_json::Value;

/// skill 目录名 —— 同时充当幂等 marker(与旧 MCP server 名一致,便于对应)。
const SKILL_DIR_NAME: &str = "mini-term-ssh";

/// SSH MCP server 在各配置文件里的固定名字 —— 同时充当幂等 marker。
const MCP_SERVER_NAME: &str = "mini-term-ssh";

// ─── 二进制 / 路径解析 ───

/// 获取 `mt-ssh-cli` sidecar 二进制的绝对路径(与主程序同目录的兄弟 bin)。
///
/// dev 下 `stage-sidecars.mjs` 把 sidecar 裸名就位到根 `target/debug`
/// (与 `mini-term.exe` 同目录),与发布包布局一致。
fn ssh_cli_binary_path() -> Result<String, String> {
    let exe = std::env::current_exe().map_err(|e| format!("无法获取当前程序路径: {}", e))?;
    let dir = exe
        .parent()
        .ok_or_else(|| "无法获取程序所在目录".to_string())?;

    let bin_name = if cfg!(windows) {
        "mt-ssh-cli.exe"
    } else {
        "mt-ssh-cli"
    };

    Ok(dir.join(bin_name).to_string_lossy().to_string())
}

/// 校验并规整项目目录路径。要求传入的是一个已存在的目录。
fn validate_project_dir(project_dir: &str) -> Result<PathBuf, String> {
    let trimmed = project_dir.trim();
    if trimmed.is_empty() {
        return Err("项目目录路径为空".to_string());
    }
    let path = PathBuf::from(trimmed);
    if !path.is_dir() {
        return Err(format!("项目目录不存在或不是文件夹: {}", trimmed));
    }
    Ok(path)
}

// ─── SKILL.md 模板 ───

fn quote_posix_single(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn quote_powershell_single(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// 渲染 SKILL.md 内容。`with_allowed_tools` 区分 Claude 版(true,skill 激活
/// 期间免审批)与 Codex 版(false,规避未知 frontmatter 字段的容忍度风险)。
///
/// 正文英文(与 MCP tool descriptions 一致,对两端 agent 触发与遵循最稳);
/// description 明确列出「远程执行 / 查日志 / 部署 / 传文件」等触发场景。
///
/// **这是用户不可见的 agent 面文案,不走 mt-i18n** —— 它必须与装机版逐字节
/// 一致(同一个项目可能被两个版本轮流启用)。
fn render_skill_md(binary_path: &str, project_token: &str, with_allowed_tools: bool) -> String {
    // Windows 版 Claude Code 的 shell 工具可能是 Bash 或 PowerShell,两个都列
    // (实测两条并列不影响 skill 加载)。allowed-tools 只描述可执行文件匹配;
    // 正文里的 PowerShell 命令仍必须带调用运算符 `&`。
    // 整行是 YAML 单引号标量:路径若含撇号(如 C:\Users\O'Brien\...)需按 YAML
    // 规则双写转义,否则 frontmatter 断裂、skill 静默加载失败。
    let allowed_tools_line = if with_allowed_tools {
        let yaml_safe = binary_path.replace('\'', "''");
        format!("allowed-tools: 'Bash(\"{yaml_safe}\" *), PowerShell(\"{yaml_safe}\" *)'\n")
    } else {
        String::new()
    };
    let bash_binary = quote_posix_single(binary_path);
    let bash_token = quote_posix_single(project_token);
    let wsl_binary = format!("\"$(wslpath {bash_binary})\"");
    let powershell_binary = quote_powershell_single(binary_path);
    let powershell_token = quote_powershell_single(project_token);
    format!(
        r#"---
name: mini-term-ssh
description: Run commands or transfer files on remote servers over SSH using this project's saved connections (managed by mini-term). Use when the user asks to operate on a remote host — run commands, inspect logs, deploy services, upload or download files.
{allowed_tools_line}---

<!-- generated by mini-term; do not edit (regenerated on enable) -->

# mini-term SSH CLI

This project has saved SSH connections managed by mini-term. Authentication is
handled internally — NEVER ask the user for passwords and NEVER use plain
`ssh` / `scp` / `sftp`.

CLI binary (quote the path, it may contain spaces):

    "{binary_path}"

All examples below already carry this project's capability token. Never replace
or omit it: the daemon rejects unknown tokens instead of exposing other projects.

## Bash / Git Bash

List available connections:

    {bash_binary} list --project-token {bash_token} --json

Run a remote command:

    {bash_binary} exec --project-token {bash_token} [--cwd DIR] [--timeout SECS] <connection> -- <command...>

Upload / download files:

    {bash_binary} upload   --project-token {bash_token} <connection> <local_path> <remote_path>
    {bash_binary} download --project-token {bash_token} <connection> <remote_path> <local_path>

## WSL (Windows interop)

    {wsl_binary} list --project-token {bash_token} --json
    {wsl_binary} exec --project-token {bash_token} [--cwd DIR] [--timeout SECS] <connection> -- <command...>
    {wsl_binary} upload   --project-token {bash_token} <connection> <local_path> <remote_path>
    {wsl_binary} download --project-token {bash_token} <connection> <remote_path> <local_path>

## PowerShell

PowerShell requires the call operator `&` before a quoted executable path:

    & {powershell_binary} list --project-token {powershell_token} --json
    & {powershell_binary} exec --project-token {powershell_token} [--cwd DIR] [--timeout SECS] <connection> -- <command...>
    & {powershell_binary} upload   --project-token {powershell_token} <connection> <local_path> <remote_path>
    & {powershell_binary} download --project-token {powershell_token} <connection> <remote_path> <local_path>

- Remote stdout/stderr stream through; exit code = remote exit code.
- Exit 124 = timeout (default 60s), exit 2 + `mt-ssh-cli: error:` on stderr = CLI/connection error.
- Large output: append `> file.log` and read the file afterwards.

Do NOT base64-echo file contents through exec — use upload/download.
"#
    )
}

/// 两份 SKILL.md 的落盘路径。
fn skill_paths(project_dir: &Path) -> [(PathBuf, bool); 2] {
    [
        (
            project_dir
                .join(".claude")
                .join("skills")
                .join(SKILL_DIR_NAME)
                .join("SKILL.md"),
            true, // Claude 版含 allowed-tools
        ),
        (
            project_dir
                .join(".codex")
                .join("skills")
                .join(SKILL_DIR_NAME)
                .join("SKILL.md"),
            false,
        ),
    ]
}

/// 整文件覆盖写入两份 SKILL.md(mini-term 独占生成物,无需合并语义)。
fn write_skill_files(
    project_dir: &Path,
    binary_path: &str,
    project_token: &str,
) -> Result<(), String> {
    for (path, with_allowed_tools) in skill_paths(project_dir) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("创建 skill 目录失败 {}: {}", parent.display(), e))?;
        }
        let content = render_skill_md(binary_path, project_token, with_allowed_tools);
        atomic_write(&path, content.as_bytes())
            .map_err(|e| format!("写入 {} 失败: {}", path.display(), e))?;
    }
    Ok(())
}

/// 删除两份 SKILL.md 及空目录:`mini-term-ssh/` 一定删;`skills/` 若空一并删;
/// `.claude/` / `.codex/` 若因此彻底变空也顺手收掉(remove_dir 只删空目录,
/// 有其它内容时静默失败,安全)。文件不存在视为已停用(幂等)。
fn remove_skill_files(project_dir: &Path) -> Result<(), String> {
    for (path, _) in skill_paths(project_dir) {
        if path.exists() {
            std::fs::remove_file(&path)
                .map_err(|e| format!("删除 {} 失败: {}", path.display(), e))?;
        }
        // mini-term-ssh/ → skills/ → .claude|.codex/,逐级尝试删空目录。
        let mut dir = path.parent();
        for _ in 0..3 {
            let Some(d) = dir else { break };
            // 只在目录存在且为空时成功;失败(非空/不存在)即停止向上。
            if std::fs::remove_dir(d).is_err() {
                break;
            }
            dir = d.parent();
        }
    }
    Ok(())
}

// ─── <project>/.gitignore ───

/// `.gitignore` 里要追加的条目(生成物含机器相关绝对路径,不该进版本库)。
const GITIGNORE_ENTRIES: &[&str] = &[
    ".claude/skills/mini-term-ssh/",
    ".codex/skills/mini-term-ssh/",
];

/// 计算追加条目后的 `.gitignore` 全文;若无需追加返回 `None`。抽出便于单测。
fn compute_gitignore_append(existing: &str) -> Option<String> {
    let present: std::collections::HashSet<&str> = existing.lines().map(|l| l.trim()).collect();
    let missing: Vec<&str> = GITIGNORE_ENTRIES
        .iter()
        .copied()
        .filter(|e| !present.contains(*e))
        .collect();
    if missing.is_empty() {
        return None;
    }

    let mut out = existing.to_string();
    // 确保与已有内容之间有换行分隔
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("# mini-term SSH skill（本机相关生成物，勿提交）\n");
    for entry in missing {
        out.push_str(entry);
        out.push('\n');
    }
    Some(out)
}

/// 幂等地把两个 skill 目录追加进 `<project>/.gitignore`。
fn append_gitignore_entries(project_dir: &Path) -> Result<(), String> {
    let gitignore_path = project_dir.join(".gitignore");
    let existing = if gitignore_path.exists() {
        std::fs::read_to_string(&gitignore_path)
            .map_err(|e| format!("读取 .gitignore 失败: {}", e))?
    } else {
        String::new()
    };

    let Some(appended) = compute_gitignore_append(&existing) else {
        return Ok(());
    };

    atomic_write(&gitignore_path, appended.as_bytes())
        .map_err(|e| format!("写入 .gitignore 失败: {}", e))?;
    Ok(())
}

// ---------------------------------------------------------------------------
// legacy MCP 读侧清理(自 `ssh_mcp_registry.rs`)
// ---------------------------------------------------------------------------
//
// 注册职责已由本模块的 SKILL.md 生成接替(ssh-cli-skill spec §5):启用/停用
// SSH 工具不再写任何 MCP 配置,这一段只保留「摘除历史 MCP 注册」的清理函数,
// 由启用/停用两条路自动迁移存量项目。
//
// 清理原则与写入时代一致:只动本 server 用 marker 写入的条目,用户/团队的
// 其它 server 与配置字段毫发无损;但**不**移除 Codex 的项目信任(无法可靠
// 区分是否本功能所加,且信任无害),也不动 `.gitignore`。

/// 获取 Codex 全局配置文件路径: `~/.codex/config.toml`
fn codex_global_config_path() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".codex").join("config.toml"))
}

/// 获取 Claude Code 全局配置文件路径: `~/.claude/settings.json`
fn claude_settings_path() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".claude").join("settings.json"))
}

/// 从 `<project>/.mcp.json` 幂等移除 `mini-term-ssh` server。
///
/// 只删本 server 的 key;若删完后 `mcpServers` 与文件都为空,则删掉整个
/// `.mcp.json`(避免留下空壳文件)。文件不存在视为已移除。
fn remove_project_mcp_json(project_dir: &Path) -> Result<(), String> {
    let mcp_path = project_dir.join(".mcp.json");
    if !mcp_path.exists() {
        return Ok(());
    }
    let content =
        std::fs::read_to_string(&mcp_path).map_err(|e| format!("读取 .mcp.json 失败: {}", e))?;
    if content.trim().is_empty() {
        // 空文件直接删
        let _ = std::fs::remove_file(&mcp_path);
        return Ok(());
    }
    let mut root: Value =
        serde_json::from_str(&content).map_err(|e| format!("解析 .mcp.json 失败: {}", e))?;

    if let Some(servers) = root.get_mut("mcpServers").and_then(|s| s.as_object_mut()) {
        servers.remove(MCP_SERVER_NAME);
    }

    if mcp_json_is_now_empty(&root) {
        std::fs::remove_file(&mcp_path).map_err(|e| format!("删除空的 .mcp.json 失败: {}", e))?;
    } else {
        let json_str = serde_json::to_string_pretty(&root)
            .map_err(|e| format!("序列化 .mcp.json 失败: {}", e))?;
        atomic_write(&mcp_path, json_str.as_bytes())
            .map_err(|e| format!("写入 .mcp.json 失败: {}", e))?;
    }
    Ok(())
}

/// 文件是否变成「只剩空 mcpServers / 空对象」—— 是则整个文件该删。抽出便于单测。
fn mcp_json_is_now_empty(root: &Value) -> bool {
    root.as_object()
        .map(|obj| {
            obj.iter().all(|(k, v)| {
                k == "mcpServers" && v.as_object().map(|m| m.is_empty()).unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

/// 从 `<project>/.codex/config.toml` 幂等移除 `[mcp_servers.mini-term-ssh]`。
///
/// 只删本 server 子表;文件其它内容保留。文件不存在视为已移除。
fn remove_project_codex_config(project_dir: &Path) -> Result<(), String> {
    let config_path = project_dir.join(".codex").join("config.toml");
    if !config_path.exists() {
        return Ok(());
    }
    let content = std::fs::read_to_string(&config_path)
        .map_err(|e| format!("读取项目 config.toml 失败: {}", e))?;
    let mut doc: toml_edit::DocumentMut = content
        .parse::<toml_edit::DocumentMut>()
        .map_err(|e| format!("解析项目 config.toml 失败: {}", e))?;

    strip_codex_mcp_server(&mut doc);

    atomic_write(&config_path, doc.to_string().as_bytes())
        .map_err(|e| format!("写入项目 config.toml 失败: {}", e))?;
    Ok(())
}

/// 在 `toml_edit` 文档里删掉 `[mcp_servers.mini-term-ssh]` 子表。抽出便于单测。
///
/// 若删完后 `mcp_servers` 表为空,连 `[mcp_servers]` 一并移除,不留空表。
fn strip_codex_mcp_server(doc: &mut toml_edit::DocumentMut) {
    if let Some(servers) = doc.get_mut("mcp_servers").and_then(|i| i.as_table_mut()) {
        servers.remove(MCP_SERVER_NAME);
        if servers.is_empty() {
            doc.remove("mcp_servers");
        }
    }
}

/// 在 Codex 全局 `~/.codex/config.toml` 里把项目标为 `trust_level = "trusted"`。
///
/// Codex 要求项目目录被信任后,其 `<project>/.codex/` 内容才生效;未信任则
/// 项目级配置(含 skills)可能被静默忽略,启用时继续写入。
///
/// 幂等:若该项目路径已有 `[projects."..."]` 条目,保留其它字段、只确保
/// `trust_level` 为 `"trusted"`。停用时**不**移除此信任(无法可靠判断是否
/// 本功能所加,且信任本身无害)。
fn trust_project_in_codex(project_dir: &Path) -> Result<(), String> {
    let config_path = codex_global_config_path().ok_or_else(|| "无法获取 home 目录".to_string())?;
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("创建 .codex 目录失败: {}", e))?;
    }

    let content = if config_path.exists() {
        std::fs::read_to_string(&config_path)
            .map_err(|e| format!("读取 Codex config.toml 失败: {}", e))?
    } else {
        String::new()
    };

    let mut doc: toml_edit::DocumentMut = content
        .parse::<toml_edit::DocumentMut>()
        .map_err(|e| format!("解析 Codex config.toml 失败: {}", e))?;

    // Codex 用项目绝对路径作为 [projects."<path>"] 的 key。
    let key = project_dir.to_string_lossy().to_string();
    apply_codex_project_trust(&mut doc, &key);

    atomic_write(&config_path, doc.to_string().as_bytes())
        .map_err(|e| format!("写入 Codex config.toml 失败: {}", e))?;
    Ok(())
}

/// 在 `toml_edit` 文档里确保 `[projects."<key>"] trust_level = "trusted"`。抽出便于单测。
fn apply_codex_project_trust(doc: &mut toml_edit::DocumentMut, project_key: &str) {
    if doc.get("projects").is_none() {
        let mut t = toml_edit::Table::new();
        t.set_implicit(true);
        doc["projects"] = toml_edit::Item::Table(t);
    }
    doc["projects"][project_key]["trust_level"] = toml_edit::value("trusted");
}

/// 在 Claude `~/.claude/settings.json` 的 `enabledMcpjsonServers` 数组里
/// 增/删本 server 名。skill 时代只用 `enable = false` 路径清理历史白名单;
/// enable 路径保留给单测与潜在回滚。
///
/// 幂等:已在/不在数组里都不重复操作。
fn set_claude_mcp_approval(enable: bool) -> Result<(), String> {
    let settings_path = claude_settings_path().ok_or_else(|| "无法获取 home 目录".to_string())?;
    if let Some(parent) = settings_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("创建 .claude 目录失败: {}", e))?;
    }

    // 停用且文件不存在 → 无需处理
    if !enable && !settings_path.exists() {
        return Ok(());
    }

    let mut settings: Value = if settings_path.exists() {
        let content = std::fs::read_to_string(&settings_path)
            .map_err(|e| format!("读取 Claude settings.json 失败: {}", e))?;
        if content.trim().is_empty() {
            serde_json::json!({})
        } else {
            serde_json::from_str(&content)
                .map_err(|e| format!("解析 Claude settings.json 失败: {}", e))?
        }
    } else {
        serde_json::json!({})
    };
    if !settings.is_object() {
        return Err("Claude settings.json 顶层不是 JSON 对象".to_string());
    }

    apply_claude_mcp_approval(&mut settings, enable);

    let json_str = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("序列化 Claude settings.json 失败: {}", e))?;
    atomic_write(&settings_path, json_str.as_bytes())
        .map_err(|e| format!("写入 Claude settings.json 失败: {}", e))?;
    Ok(())
}

/// 在 settings JSON 里增/删 `enabledMcpjsonServers` 中的本 server 名。抽出便于单测。
fn apply_claude_mcp_approval(settings: &mut Value, enable: bool) {
    if enable {
        if settings.get("enabledMcpjsonServers").is_none() {
            settings["enabledMcpjsonServers"] = serde_json::json!([]);
        }
        if let Some(arr) = settings["enabledMcpjsonServers"].as_array_mut() {
            let already = arr.iter().any(|v| v.as_str() == Some(MCP_SERVER_NAME));
            if !already {
                arr.push(Value::String(MCP_SERVER_NAME.to_string()));
            }
        }
    } else if let Some(arr) = settings
        .get_mut("enabledMcpjsonServers")
        .and_then(|v| v.as_array_mut())
    {
        arr.retain(|v| v.as_str() != Some(MCP_SERVER_NAME));
    }
}

/// 摘除该项目的旧 MCP 注册(存量项目从 MCP 切到 skill 的自动迁移)。
///
/// 只删本 server 的条目/白名单项,`.mcp.json` 里其它 server 与用户配置毫发无损。
fn cleanup_legacy_mcp(project_dir: &Path) -> Result<(), String> {
    remove_project_mcp_json(project_dir)?;
    remove_project_codex_config(project_dir)?;
    set_claude_mcp_approval(false)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// 公开入口(原 `enable_ssh_tools` / `disable_ssh_tools` 两个 command)
// ---------------------------------------------------------------------------

/// [`enable`] 的返回值。调用方必须把 `project_token` 持久化进对应项目配置
/// (`ProjectConfig::ssh_cli_token`),daemon 才能把令牌解析回项目范围。
#[derive(Debug, Clone)]
pub struct EnableResult {
    /// 面向用户的成功提示(中文,与装机版一字不差,故不走 mt-i18n)。
    pub message: String,
    pub project_token: String,
}

/// 复用已有非空令牌;存量项目没有令牌时生成新的 UUID v4 能力令牌。
fn resolve_project_token(existing: Option<&str>) -> String {
    existing
        .map(|token| token.trim().to_string())
        .filter(|token| !token.is_empty())
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string())
}

/// 为指定项目启用 SSH 工具(CLI + Skill)。
///
/// `project_dir` 为项目目录绝对路径;已有 `project_token` 会稳定复用,存量项目
/// 缺失时生成新的能力令牌并写死进 SKILL.md。成功后该项目里新启动的
/// Claude Code / Codex 会话即可通过 skill 调用 SSH CLI(已运行的会话需重启)。
///
/// **阻塞**,丢 `background_executor`。
pub fn enable(project_dir: &str, project_token: Option<&str>) -> Result<EnableResult, String> {
    let dir = validate_project_dir(project_dir)?;
    let project_token = resolve_project_token(project_token);
    let binary_path = ssh_cli_binary_path()?;

    // 核心写入:任何一步失败都直接返回错误(可读中文)。
    write_skill_files(&dir, &binary_path, &project_token)?;
    trust_project_in_codex(&dir)?;
    // 存量项目自动摘除旧 MCP 注册(新项目本就没有,天然幂等)。
    cleanup_legacy_mcp(&dir)?;

    // .gitignore 追加属于附带优化,失败不致命:记 stderr 并在结果里提示。
    let gitignore_note = match append_gitignore_entries(&dir) {
        Ok(()) => String::new(),
        Err(e) => {
            eprintln!("[ssh_skill] 追加 .gitignore 失败(不影响启用): {}", e);
            "（.gitignore 未能自动更新，建议手动忽略两个 skills/mini-term-ssh/ 目录）".to_string()
        }
    };

    Ok(EnableResult {
        message: format!(
            "已为该项目启用 SSH 工具：已生成 Claude / Codex 两份 SKILL.md。{}",
            gitignore_note
        ),
        project_token,
    })
}

/// 为指定项目停用 SSH 工具。
///
/// 删除本功能生成的 SKILL.md 与空目录,并兜底清理历史遗留的 MCP 注册;
/// Codex 项目信任与 `.gitignore` 条目保留(无害,且无法可靠区分是否本功能所加)。
///
/// **阻塞**,丢 `background_executor`。
pub fn disable(project_dir: &str) -> Result<String, String> {
    let dir = validate_project_dir(project_dir)?;

    remove_skill_files(&dir)?;
    cleanup_legacy_mcp(&dir)?;

    Ok("已为该项目停用 SSH 工具：已删除生成的 SKILL.md 并清理历史 MCP 注册。".to_string())
}

// ---------------------------------------------------------------------------
// tests(自两个原版模块的测试逐条搬来;不碰真实 home 目录)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn unique_test_dir(label: &str) -> PathBuf {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("mt-ssh-skill-test-{label}-{ts}"));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    const WIN_BIN: &str = r"C:\Program Files\mini term\mt-ssh-cli.exe";

    // ─── SKILL.md 渲染 ───

    #[test]
    fn skill_md_embeds_binary_path_and_project_token() {
        let md = render_skill_md(WIN_BIN, "token-1", true);
        // Windows 路径原样嵌入(含空格与反斜杠,使用处都带引号)
        assert!(md.contains(&format!("\"{WIN_BIN}\"")), "got:\n{md}");
        assert!(md.contains("--project-token 'token-1'"));
        assert!(!md.contains("--project-id"));
        // 四个子命令的示例都在
        assert!(md.contains(" list "));
        assert!(md.contains(" exec "));
        assert!(md.contains(" upload "));
        assert!(md.contains(" download "));
        // generated 头注释标记
        assert!(md.contains("<!-- generated by mini-term"));
        // WSL interop 用法
        assert!(md.contains("wslpath"));
    }

    #[test]
    fn skill_md_frontmatter_differs_between_claude_and_codex() {
        let claude = render_skill_md(WIN_BIN, "p", true);
        let codex = render_skill_md(WIN_BIN, "p", false);
        // Claude 版含 allowed-tools(带引号包住可能含空格的路径,Bash/PowerShell 双条目)
        assert!(claude.contains(&format!(
            "allowed-tools: 'Bash(\"{WIN_BIN}\" *), PowerShell(\"{WIN_BIN}\" *)'"
        )));
        assert!(!codex.contains("allowed-tools"));
        // 公共 frontmatter 两版都有
        for md in [&claude, &codex] {
            assert!(md.starts_with("---\nname: mini-term-ssh\n"));
            assert!(md.contains("description: Run commands or transfer files"));
        }
    }

    #[test]
    fn skill_md_escapes_apostrophe_in_path_for_yaml() {
        // 撇号路径(如 O'Brien 用户名)在 YAML 单引号标量里必须双写,
        // 否则 frontmatter 断裂导致 skill 加载失败。
        let md = render_skill_md(r"C:\Users\O'Brien\mt-ssh-cli.exe", "p", true);
        assert!(
            md.contains(r#"Bash("C:\Users\O''Brien\mt-ssh-cli.exe" *)"#),
            "got:\n{md}"
        );
        // 正文(单引号标量之外)保留原始撇号
        assert!(md.contains(r#"    "C:\Users\O'Brien\mt-ssh-cli.exe""#));
    }

    #[test]
    fn skill_md_powershell_examples_use_call_operator() {
        let md = render_skill_md(WIN_BIN, "token-1", true);
        assert!(
            md.contains(
                r#"& 'C:\Program Files\mini term\mt-ssh-cli.exe' list --project-token 'token-1'"#
            ),
            "got:\n{md}"
        );
    }

    #[test]
    fn skill_md_shell_quotes_apostrophe_paths() {
        let path = r"C:\Users\O'Brien\mt-ssh-cli.exe";
        let md = render_skill_md(path, "token-1", true);
        assert!(
            md.contains(r#"wslpath 'C:\Users\O'"'"'Brien\mt-ssh-cli.exe'"#),
            "got:\n{md}"
        );
        assert!(
            md.contains(r#"& 'C:\Users\O''Brien\mt-ssh-cli.exe' list --project-token 'token-1'"#),
            "got:\n{md}"
        );
    }

    #[test]
    fn skill_md_contains_no_sensitive_fields() {
        // 模板只接收二进制路径与 project token 两个注入值,不可能携带 SSH 凭据;
        // 正文提到 "passwords" 仅出现在「绝不向用户要密码」的指引行里。
        let md = render_skill_md(WIN_BIN, "p", true);
        assert!(!md.contains("identityFile"));
        for line in md.lines().filter(|l| l.to_lowercase().contains("password")) {
            assert!(
                line.contains("NEVER ask the user for passwords"),
                "unexpected: {line}"
            );
        }
    }

    // ─── 写入 / 覆盖 / 清理 ───

    #[test]
    fn write_skill_files_creates_both_variants() {
        let dir = unique_test_dir("write");
        write_skill_files(&dir, "/bin/mt-ssh-cli", "p1").unwrap();

        let claude = dir
            .join(".claude")
            .join("skills")
            .join(SKILL_DIR_NAME)
            .join("SKILL.md");
        let codex = dir
            .join(".codex")
            .join("skills")
            .join(SKILL_DIR_NAME)
            .join("SKILL.md");
        assert!(claude.exists());
        assert!(codex.exists());
        let claude_md = std::fs::read_to_string(&claude).unwrap();
        let codex_md = std::fs::read_to_string(&codex).unwrap();
        assert!(claude_md.contains("allowed-tools"));
        assert!(!codex_md.contains("allowed-tools"));
        assert!(claude_md.contains("--project-token 'p1'"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_skill_files_overwrite_is_idempotent() {
        // 整文件覆盖:改 project token 后重写,旧内容不残留。
        let dir = unique_test_dir("overwrite");
        write_skill_files(&dir, "/bin/mt-ssh-cli", "old-pid").unwrap();
        write_skill_files(&dir, "/bin/mt-ssh-cli", "new-pid").unwrap();

        let md = std::fs::read_to_string(
            dir.join(".claude")
                .join("skills")
                .join(SKILL_DIR_NAME)
                .join("SKILL.md"),
        )
        .unwrap();
        assert!(md.contains("--project-token 'new-pid'"));
        assert!(!md.contains("old-pid"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn remove_skill_files_cleans_files_and_empty_dirs() {
        let dir = unique_test_dir("remove");
        write_skill_files(&dir, "/bin/mt-ssh-cli", "p1").unwrap();
        remove_skill_files(&dir).unwrap();

        // SKILL.md、mini-term-ssh/、skills/ 乃至空的 .claude/.codex 都不残留
        assert!(!dir.join(".claude").exists(), "空壳目录应被清理");
        assert!(!dir.join(".codex").exists(), "空壳目录应被清理");
        // 项目目录本身不受影响
        assert!(dir.exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn remove_skill_files_keeps_sibling_content() {
        // .claude/ 里有用户自己的文件时,只删本 skill,不动其它内容。
        let dir = unique_test_dir("keep-sibling");
        write_skill_files(&dir, "/bin/mt-ssh-cli", "p1").unwrap();
        std::fs::write(dir.join(".claude").join("settings.local.json"), b"{}").unwrap();
        let other_skill = dir.join(".claude").join("skills").join("my-skill");
        std::fs::create_dir_all(&other_skill).unwrap();
        std::fs::write(other_skill.join("SKILL.md"), b"mine").unwrap();

        remove_skill_files(&dir).unwrap();

        assert!(
            !dir.join(".claude")
                .join("skills")
                .join(SKILL_DIR_NAME)
                .exists()
        );
        // 用户内容毫发无损
        assert!(dir.join(".claude").join("settings.local.json").exists());
        assert!(other_skill.join("SKILL.md").exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn remove_skill_files_is_idempotent_when_absent() {
        let dir = unique_test_dir("remove-absent");
        // 从未启用过 → 直接停用不报错
        remove_skill_files(&dir).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
    }

    // ─── .gitignore 追加 ───

    #[test]
    fn gitignore_append_on_empty_adds_both_entries() {
        let result = compute_gitignore_append("").unwrap();
        assert!(result.contains(".claude/skills/mini-term-ssh/"));
        assert!(result.contains(".codex/skills/mini-term-ssh/"));
    }

    #[test]
    fn gitignore_append_skips_existing_entries() {
        let existing =
            "node_modules\n.claude/skills/mini-term-ssh/\n.codex/skills/mini-term-ssh/\n";
        assert!(compute_gitignore_append(existing).is_none());
    }

    #[test]
    fn gitignore_append_adds_only_missing_entry() {
        let existing = "node_modules\n.claude/skills/mini-term-ssh/\n";
        let result = compute_gitignore_append(existing).unwrap();
        assert!(result.contains("node_modules"));
        assert!(result.contains(".codex/skills/mini-term-ssh/"));
        // 已有条目不重复
        assert_eq!(result.matches(".claude/skills/mini-term-ssh/").count(), 1);
    }

    #[test]
    fn gitignore_append_file_round_trip_idempotent() {
        let dir = unique_test_dir("gitignore");
        std::fs::write(dir.join(".gitignore"), "node_modules\n").unwrap();

        append_gitignore_entries(&dir).unwrap();
        append_gitignore_entries(&dir).unwrap();

        let content = std::fs::read_to_string(dir.join(".gitignore")).unwrap();
        assert!(content.contains("node_modules"));
        assert_eq!(content.matches(".claude/skills/mini-term-ssh/").count(), 1);
        assert_eq!(content.matches(".codex/skills/mini-term-ssh/").count(), 1);

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ─── validate_project_dir ───

    #[test]
    fn validate_project_dir_rejects_empty_and_missing() {
        assert!(validate_project_dir("").is_err());
        assert!(validate_project_dir("   ").is_err());
        assert!(validate_project_dir("/definitely/not/a/real/dir/xyz123").is_err());
    }

    #[test]
    fn validate_project_dir_accepts_existing_dir() {
        let tmp = std::env::temp_dir();
        assert!(validate_project_dir(&tmp.to_string_lossy()).is_ok());
    }

    #[test]
    fn project_token_reuses_existing_or_generates_uuid() {
        assert_eq!(
            resolve_project_token(Some("  existing-token  ")),
            "existing-token"
        );
        let generated = resolve_project_token(None);
        assert!(uuid::Uuid::parse_str(&generated).is_ok(), "got: {generated}");
        // 空串等同于「没有令牌」,必须生成新的而不是落一个空 token
        assert!(uuid::Uuid::parse_str(&resolve_project_token(Some("   "))).is_ok());
    }

    // ─── .mcp.json 移除逻辑 ───

    /// 镜像 remove_project_mcp_json 的纯逻辑:返回 (剩余内容, 是否应删文件)。
    fn mcp_json_after_remove(initial: &str) -> (Value, bool) {
        let mut root: Value = serde_json::from_str(initial).unwrap();
        if let Some(servers) = root.get_mut("mcpServers").and_then(|s| s.as_object_mut()) {
            servers.remove(MCP_SERVER_NAME);
        }
        let is_now_empty = mcp_json_is_now_empty(&root);
        (root, is_now_empty)
    }

    #[test]
    fn mcp_json_remove_keeps_other_servers() {
        let initial =
            r#"{"mcpServers":{"mini-term-ssh":{"command":"x"},"other":{"command":"y"}}}"#;
        let (root, should_delete) = mcp_json_after_remove(initial);
        assert!(!should_delete);
        assert!(root["mcpServers"].get("mini-term-ssh").is_none());
        assert_eq!(root["mcpServers"]["other"]["command"], "y");
    }

    #[test]
    fn mcp_json_remove_signals_delete_when_only_our_server() {
        let initial = r#"{"mcpServers":{"mini-term-ssh":{"command":"x"}}}"#;
        let (_root, should_delete) = mcp_json_after_remove(initial);
        // 删完后只剩空 mcpServers → 应删整个文件
        assert!(should_delete);
    }

    #[test]
    fn mcp_json_remove_keeps_file_when_other_top_level_keys() {
        let initial = r#"{"mcpServers":{"mini-term-ssh":{"command":"x"}},"someOtherKey":1}"#;
        let (_root, should_delete) = mcp_json_after_remove(initial);
        // 还有别的顶层 key → 不删文件
        assert!(!should_delete);
    }

    // ─── 文件级 round-trip ───

    #[test]
    fn remove_project_mcp_json_deletes_file_when_only_our_server() {
        let dir = unique_test_dir("delete-empty");
        std::fs::write(
            dir.join(".mcp.json"),
            r#"{"mcpServers":{"mini-term-ssh":{"command":"x"}}}"#,
        )
        .unwrap();
        remove_project_mcp_json(&dir).unwrap();
        assert!(
            !dir.join(".mcp.json").exists(),
            "只剩本 server 时应删除整个文件"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn remove_project_mcp_json_preserves_user_server() {
        let dir = unique_test_dir("preserve");
        std::fs::write(
            dir.join(".mcp.json"),
            r#"{"mcpServers":{"mini-term-ssh":{"command":"x"},"team-server":{"command":"team"}}}"#,
        )
        .unwrap();
        remove_project_mcp_json(&dir).unwrap();
        let mcp: Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join(".mcp.json")).unwrap()).unwrap();
        assert_eq!(mcp["mcpServers"]["team-server"]["command"], "team");
        assert!(mcp["mcpServers"].get(MCP_SERVER_NAME).is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn remove_project_mcp_json_noop_when_absent() {
        let dir = unique_test_dir("absent");
        remove_project_mcp_json(&dir).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn remove_project_codex_config_strips_only_our_table() {
        let dir = unique_test_dir("codex");
        std::fs::create_dir_all(dir.join(".codex")).unwrap();
        std::fs::write(
            dir.join(".codex").join("config.toml"),
            "[mcp_servers.context7]\ncommand = \"npx\"\n\n[mcp_servers.mini-term-ssh]\ncommand = \"/bin/mt-ssh-mcp\"\n",
        )
        .unwrap();
        remove_project_codex_config(&dir).unwrap();
        let doc: toml_edit::DocumentMut =
            std::fs::read_to_string(dir.join(".codex").join("config.toml"))
                .unwrap()
                .parse()
                .unwrap();
        assert!(doc["mcp_servers"].get("mini-term-ssh").is_none());
        assert_eq!(
            doc["mcp_servers"]["context7"]["command"].as_str(),
            Some("npx")
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    // ─── Codex config.toml 纯逻辑 ───

    #[test]
    fn codex_mcp_server_strip_removes_only_our_server() {
        let initial = "[mcp_servers.context7]\ncommand = \"npx\"\n\n[mcp_servers.mini-term-ssh]\ncommand = \"/bin/mt-ssh-mcp\"\n";
        let mut doc: toml_edit::DocumentMut = initial.parse().unwrap();
        strip_codex_mcp_server(&mut doc);
        let reparsed: toml_edit::DocumentMut = doc.to_string().parse().unwrap();
        assert!(reparsed["mcp_servers"].get("mini-term-ssh").is_none());
        // 别的 server 保留
        assert_eq!(
            reparsed["mcp_servers"]["context7"]["command"].as_str(),
            Some("npx")
        );
    }

    #[test]
    fn codex_mcp_server_strip_removes_empty_table() {
        let initial = "[mcp_servers.mini-term-ssh]\ncommand = \"/bin/mt-ssh-mcp\"\n";
        let mut doc: toml_edit::DocumentMut = initial.parse().unwrap();
        strip_codex_mcp_server(&mut doc);
        // 删完后整个 mcp_servers 表应消失
        assert!(doc.get("mcp_servers").is_none());
    }

    #[test]
    fn codex_mcp_server_strip_noop_when_absent() {
        let initial = "[mcp_servers.context7]\ncommand = \"npx\"\n";
        let mut doc: toml_edit::DocumentMut = initial.parse().unwrap();
        strip_codex_mcp_server(&mut doc);
        let reparsed: toml_edit::DocumentMut = doc.to_string().parse().unwrap();
        // 别人的 server 不受影响
        assert_eq!(
            reparsed["mcp_servers"]["context7"]["command"].as_str(),
            Some("npx")
        );
    }

    // ─── Codex 项目信任 ───

    #[test]
    fn codex_project_trust_written_correctly() {
        let mut doc: toml_edit::DocumentMut = "".parse().unwrap();
        apply_codex_project_trust(&mut doc, r"D:\Git\proj");
        let reparsed: toml_edit::DocumentMut = doc.to_string().parse().unwrap();
        assert_eq!(
            reparsed["projects"][r"D:\Git\proj"]["trust_level"].as_str(),
            Some("trusted")
        );
    }

    #[test]
    fn codex_project_trust_preserves_other_projects() {
        let initial = "[projects.\"/home/u/other\"]\ntrust_level = \"trusted\"\n";
        let mut doc: toml_edit::DocumentMut = initial.parse().unwrap();
        apply_codex_project_trust(&mut doc, "/home/u/new");
        let reparsed: toml_edit::DocumentMut = doc.to_string().parse().unwrap();
        // 旧项目信任保留
        assert_eq!(
            reparsed["projects"]["/home/u/other"]["trust_level"].as_str(),
            Some("trusted")
        );
        // 新项目信任加入
        assert_eq!(
            reparsed["projects"]["/home/u/new"]["trust_level"].as_str(),
            Some("trusted")
        );
    }

    #[test]
    fn codex_project_trust_preserves_sibling_fields() {
        // 已有项目条目带其它字段时,只动 trust_level,其它字段保留
        let initial = "[projects.\"/home/u/proj\"]\ntrust_level = \"unknown\"\nsome_field = 42\n";
        let mut doc: toml_edit::DocumentMut = initial.parse().unwrap();
        apply_codex_project_trust(&mut doc, "/home/u/proj");
        let reparsed: toml_edit::DocumentMut = doc.to_string().parse().unwrap();
        assert_eq!(
            reparsed["projects"]["/home/u/proj"]["trust_level"].as_str(),
            Some("trusted")
        );
        assert_eq!(
            reparsed["projects"]["/home/u/proj"]["some_field"].as_integer(),
            Some(42)
        );
    }

    // ─── Claude enabledMcpjsonServers ───

    #[test]
    fn claude_approval_enable_adds_server_name() {
        let mut settings = serde_json::json!({});
        apply_claude_mcp_approval(&mut settings, true);
        let arr = settings["enabledMcpjsonServers"].as_array().unwrap();
        assert_eq!(arr.len(), 1);
        assert_eq!(arr[0], MCP_SERVER_NAME);
    }

    #[test]
    fn claude_approval_disable_removes_only_our_server() {
        let mut settings =
            serde_json::json!({ "enabledMcpjsonServers": ["memory", MCP_SERVER_NAME, "github"] });
        apply_claude_mcp_approval(&mut settings, false);
        let arr = settings["enabledMcpjsonServers"].as_array().unwrap();
        assert_eq!(arr.len(), 2);
        assert!(!arr.iter().any(|v| v == MCP_SERVER_NAME));
    }

    #[test]
    fn claude_approval_disable_noop_when_absent() {
        let mut settings = serde_json::json!({ "enabledMcpjsonServers": ["memory"] });
        apply_claude_mcp_approval(&mut settings, false);
        assert_eq!(
            settings["enabledMcpjsonServers"].as_array().unwrap().len(),
            1
        );
    }

    #[test]
    fn claude_approval_preserves_unrelated_settings() {
        let mut settings = serde_json::json!({ "theme": "dark", "hooks": {} });
        apply_claude_mcp_approval(&mut settings, false);
        // 不相关的 key 不受影响
        assert_eq!(settings["theme"], "dark");
        assert!(settings["hooks"].is_object());
    }

    // ─── 存量 MCP 项目迁移 round-trip ───

    #[test]
    fn enable_over_legacy_mcp_project_migrates_and_preserves_others() {
        let dir = unique_test_dir("migrate");
        // 存量项目:.mcp.json 里有本 server + 团队共享 server;项目级 Codex 配置也有两者。
        std::fs::write(
            dir.join(".mcp.json"),
            r#"{"mcpServers":{"mini-term-ssh":{"command":"old-mcp"},"team-server":{"command":"team"}}}"#,
        )
        .unwrap();
        std::fs::create_dir_all(dir.join(".codex")).unwrap();
        std::fs::write(
            dir.join(".codex").join("config.toml"),
            "[mcp_servers.context7]\ncommand = \"npx\"\n\n[mcp_servers.mini-term-ssh]\ncommand = \"old-mcp\"\n",
        )
        .unwrap();

        // 模拟启用的项目级步骤:写 skill + 摘除项目级 MCP 注册
        // (用户级 settings.json 清理不在本测试范围,避免动真实 home 目录)。
        write_skill_files(&dir, "/bin/mt-ssh-cli", "p1").unwrap();
        remove_project_mcp_json(&dir).unwrap();
        remove_project_codex_config(&dir).unwrap();

        // skill 就位
        assert!(
            dir.join(".claude")
                .join("skills")
                .join(SKILL_DIR_NAME)
                .join("SKILL.md")
                .exists()
        );
        // .mcp.json:本 server 条目消失,团队 server 毫发无损
        let mcp: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join(".mcp.json")).unwrap()).unwrap();
        assert!(mcp["mcpServers"].get("mini-term-ssh").is_none());
        assert_eq!(mcp["mcpServers"]["team-server"]["command"], "team");
        // Codex 项目配置:本 server 子表消失,其它保留
        let codex: toml_edit::DocumentMut =
            std::fs::read_to_string(dir.join(".codex").join("config.toml"))
                .unwrap()
                .parse()
                .unwrap();
        assert!(codex["mcp_servers"].get("mini-term-ssh").is_none());
        assert_eq!(
            codex["mcp_servers"]["context7"]["command"].as_str(),
            Some("npx")
        );

        // 停用:skill 清干净,.mcp.json 的团队 server 仍在
        remove_skill_files(&dir).unwrap();
        remove_project_mcp_json(&dir).unwrap();
        assert!(!dir.join(".claude").exists());
        let mcp2: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join(".mcp.json")).unwrap()).unwrap();
        assert_eq!(mcp2["mcpServers"]["team-server"]["command"], "team");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
